"""Updated db's to add player specific table and update relationships

Revision ID: 0df54959575f
Revises: a3459231f45d
Create Date: 2023-10-04 17:59:51.474455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0df54959575f'
down_revision = 'a3459231f45d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players_in_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.String(length=120), nullable=False),
    sa.Column('player_position', sa.String(length=60), nullable=False),
    sa.Column('player_team', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['user_teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_teams', schema=None) as batch_op:
        batch_op.drop_column('players')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('players', sa.VARCHAR(length=2000), autoincrement=False, nullable=False))

    op.drop_table('players_in_teams')
    # ### end Alembic commands ###
